"""init

Revision ID: 29320e97b621
Revises: 
Create Date: 2025-07-25 18:07:46.848137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29320e97b621'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('sentiment_scores', sa.Text(), nullable=True))
    op.add_column('time_slots', sa.Column('sentiment_decision', sa.String(length=50), nullable=True))
    op.drop_column('time_slots', 'emotions_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('emotions_data', mysql.TEXT(), nullable=True))
    op.drop_column('time_slots', 'sentiment_decision')
    op.drop_column('time_slots', 'sentiment_scores'),
    op.create_table('transcript',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('transcript_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('emotions', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('transcript_id'), 'transcript', ['transcript_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timeslot_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['timeslot_id'], ['time_slots.id'], name=op.f('transcripts_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('transcripts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
